export type CategorySlug =
  | "restaurants"
  | "breweries-wineries"
  | "things-to-do"
  | "services"
  | "shopping"
  | "lodging";

export interface Category {
  slug: CategorySlug;
  label: string;
  emoji: string;
  shortDescription: string;
  longDescription: string;
}

export const CATEGORIES: Category[] = [
  {
    slug: "restaurants",
    label: "Restaurants & Cafés",
    emoji: "🍽",
    shortDescription:
      "Where to eat in Waconia, from lakefront dining to downtown breakfast.",
    longDescription:
      "Downtown Waconia has most of the restaurants within a few blocks: Iron Tap for craft beer and barbecue, Bode Gray's for pizza and Italian, Pangea Cafe for breakfast and lunch, and D'Vinci's, open since 1986. Lola's Lakehouse is the lakefront option.",
  },
  {
    slug: "breweries-wineries",
    label: "Breweries, Wineries & Distilleries",
    emoji: "🍺",
    shortDescription:
      "Wineries and house-brewed beer around Waconia.",
    longDescription:
      "Three wineries are close to town: Schram Vineyards west of Waconia, which also brews its own beer; Sovereign Estate on the north shore of Lake Waconia; and Parley Lake Winery at Deardorff Orchards. Downtown's Waconia Brewing Co. closed in January 2026, and J. Carver Distillery announced it will close by the end of October 2026.",
  },
  {
    slug: "things-to-do",
    label: "Things to Do",
    emoji: "🎯",
    shortDescription:
      "Movies, bowling, golf, events — entertainment options around Waconia.",
    longDescription:
      "Beyond the lake: Emagine's movie theater downtown, six lanes of bowling at Garage Bar & Bowl, Island View Golf Club, Safari Island's indoor pool and gym, Waconia Ice Arena, and the free Carver County Historical Society museum.",
  },
  {
    slug: "services",
    label: "Local Services",
    emoji: "🛠",
    shortDescription:
      "Government services, salons, healthcare, and everyday essentials.",
    longDescription:
      "Everyday services in Waconia: the deputy registrar for tabs and titles, Ridgeview Medical Center and Lakeview Clinic, the public library and the school district office.",
  },
  {
    slug: "shopping",
    label: "Shopping & Grocery",
    emoji: "🛍",
    shortDescription:
      "Grocery stores, boutiques, hardware, and everyday shopping in Waconia.",
    longDescription:
      "Groceries and everyday shopping: Mackenthun's Fine Foods, Aldi and Target, most of them near Marketplace Drive and Highway 5.",
  },
  {
    slug: "lodging",
    label: "Lodging",
    emoji: "🛏",
    shortDescription:
      "Hotels and lakeside short-term rentals in and near Waconia.",
    longDescription:
      "AmeriVu Inn & Suites is in Waconia. Lakefront short-term rentals are listed on Airbnb and VRBO, and Chaska and Chanhassen, a short drive east, have more hotels.",
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export interface Business {
  slug: string;
  name: string;
  category: string;            // legacy display string (e.g. "DINING")
  categoryLabel: string;       // legacy display label (e.g. "Restaurant & Bar")
  categorySlugs: CategorySlug[]; // canonical category memberships
  priceLevel: string;
  shortDescription: string;
  description: string;
  address: string;
  lat: number;
  lng: number;
  phone: string;
  website: string;
  hours: { day: string; hours: string }[];
  tips: { title: string; description: string }[];
  whatToExpect: {
    atmosphere: string;
    crowd: string;
    liveEvents: string;
    outdoorSeating: string;
  };
  image: string;
}

const STANDARD_HOURS_24: { day: string; hours: string }[] = [
  { day: "Monday", hours: "24 hours" },
  { day: "Tuesday", hours: "24 hours" },
  { day: "Wednesday", hours: "24 hours" },
  { day: "Thursday", hours: "24 hours" },
  { day: "Friday", hours: "24 hours" },
  { day: "Saturday", hours: "24 hours" },
  { day: "Sunday", hours: "24 hours" },
];

const HOURS_VARIES: { day: string; hours: string }[] = [
  { day: "Monday", hours: "See website" },
  { day: "Tuesday", hours: "See website" },
  { day: "Wednesday", hours: "See website" },
  { day: "Thursday", hours: "See website" },
  { day: "Friday", hours: "See website" },
  { day: "Saturday", hours: "See website" },
  { day: "Sunday", hours: "See website" },
];

export const businesses: Business[] = [
  {
    slug: "iron-tap",
    name: "Iron Tap",
    category: "DINING",
    categoryLabel: "Restaurant & Bar",
    categorySlugs: ["restaurants"],
    priceLevel: "$$",
    shortDescription: "Craft beer and barbecue, 38 taps, downtown",
    description:
      "A downtown restaurant and bar on West Main Street billing itself as craft brew and BBQ, with up to 38 beers on tap that change often, craft cocktails, and seasonal rooftop and patio seating. Closed Mondays.",
    address: "140 W Main St, Waconia, MN 55387",
    lat: 44.8497,
    lng: -93.7877,
    phone: "(952) 442-4447",
    website: "irontapmn.com",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "11am–8pm" },
      { day: "Wednesday", hours: "11am–8pm" },
      { day: "Thursday", hours: "11am–8pm" },
      { day: "Friday", hours: "11am–9pm" },
      { day: "Saturday", hours: "11am–9pm" },
      { day: "Sunday", hours: "11am–8pm" },
    ],
    tips: [
      { title: "Burger & Beer Tuesday", description: "Iron Tap runs a $12 burger and beer night every Tuesday." },
      { title: "Reservations by Phone", description: "Reservations are taken by phone at (952) 442-4447." },
      { title: "Rooftop and Patio", description: "Rooftop and patio seating is open in season." },
    ],
    whatToExpect: {
      atmosphere: "Downtown restaurant and bar",
      crowd: "Locals and visitors",
      liveEvents: "See website",
      outdoorSeating: "Seasonal rooftop and patio",
    },
    image: "/images/dining-iron-tap.webp",
  },
  {
    slug: "parley-lake-winery",
    name: "Parley Lake Winery",
    category: "BARS",
    categoryLabel: "Winery",
    categorySlugs: ["breweries-wineries", "things-to-do"],
    priceLevel: "$$",
    shortDescription: "Seasonal farm winery on a historic orchard",
    description:
      "A farm winery in the 1888 barn at Deardorff Orchards west of Waconia, established in 2008. Wines from cold-climate Minnesota grapes grown on the farm, a wrap-around deck overlooking the Lake View Stage and Itasca vineyard, an art gallery featuring local artists, and live music in season. Family-friendly and dog-friendly.",
    address: "8280 Parley Lake Rd, Waconia, MN 55387",
    lat: 44.876,
    lng: -93.822,
    phone: "",
    website: "parleylakewinery.com",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "Closed" },
      { day: "Wednesday", hours: "Closed" },
      { day: "Thursday", hours: "Closed" },
      { day: "Friday", hours: "4pm–8pm" },
      { day: "Saturday", hours: "12pm–6pm" },
      { day: "Sunday", hours: "12pm–6pm" },
    ],
    tips: [
      { title: "Pair with Apple Picking", description: "Deardorff Orchards is on the same farm. Pick apples first, then finish with a glass on the deck." },
      { title: "Seasonal Hours", description: "Regular Friday–Sunday hours start the first weekend in May; the winery reopens in April for special events. Check the website before driving out." },
      { title: "Groups Need a Reservation", description: "The winery requires reservations for larger groups and does not allow party buses. Email info@parleylake.com." },
    ],
    whatToExpect: {
      atmosphere: "Rustic farm winery with vineyard views",
      crowd: "Orchard visitors, families, wine drinkers",
      liveEvents: "Live music on the Lake View Stage in season",
      outdoorSeating: "Wrap-around deck overlooking the vineyard",
    },
    image: "/images/brewing-waconia.webp",
  },
  {
    slug: "schram-vineyards",
    name: "Schram Vineyards Winery & Brewery",
    category: "BARS",
    categoryLabel: "Winery & Brewery",
    categorySlugs: ["breweries-wineries", "things-to-do"],
    priceLevel: "$$",
    shortDescription: "Estate winery + brewery on rolling farmland",
    description:
      "A 32-acre winery, brewery and restaurant west of Waconia overlooking Reitz Lake, with 10 acres of cold-hardy grapes grown on site. House-brewed beer is served at Bonfire & Barrel, and the Vineyard Lodge has live music nearly every weekend, year-round.",
    address: "8785 Airport Rd, Waconia, MN 55387",
    lat: 44.8773,
    lng: -93.8392,
    phone: "(952) 492-1259",
    website: "schramvineyards.com",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "2pm–9pm" },
      { day: "Wednesday", hours: "2pm–9pm" },
      { day: "Thursday", hours: "12pm–9pm" },
      { day: "Friday", hours: "12pm–10pm" },
      { day: "Saturday", hours: "11am–10pm" },
      { day: "Sunday", hours: "11am–7pm" },
    ],
    tips: [
      { title: "Hours Differ by Building", description: "The hours shown are for the tasting room, gift shop and Bonfire & Barrel. The Vineyard Lodge keeps shorter hours." },
      { title: "Happy Hour", description: "Happy hour is 4–6pm Tuesday through Thursday." },
      { title: "Winter Lodge", description: "From December through February the Winter Lodge runs seasonal events and live music." },
    ],
    whatToExpect: {
      atmosphere: "Rural winery with lake and vineyard views",
      crowd: "Couples, friend groups, wedding parties",
      liveEvents: "Live music nearly every weekend",
      outdoorSeating: "Gazebo rentals May–October",
    },
    image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80",
  },
  {
    slug: "sovereign-estate-wine",
    name: "Sovereign Estate Winery",
    category: "BARS",
    categoryLabel: "Lakefront Winery",
    categorySlugs: ["breweries-wineries", "things-to-do"],
    priceLevel: "$$$",
    shortDescription: "Lakefront winery on the north shore of Lake Waconia",
    description:
      "A lakefront vineyard and winery on the north shore of Lake Waconia, growing cold-climate grapes including Marquette, La Crescent, Itasca and the Frontenac varieties. It has a patio over the lake and takes reservations through Tock. Sovereign no longer hosts wedding receptions.",
    address: "9950 N Shore Rd, Waconia, MN 55387",
    lat: 44.8772,
    lng: -93.7991,
    phone: "(952) 446-9957",
    website: "sovereignestatewine.com",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "12pm–6pm" },
      { day: "Wednesday", hours: "12pm–8pm" },
      { day: "Thursday", hours: "12pm–8pm" },
      { day: "Friday", hours: "12pm–9pm" },
      { day: "Saturday", hours: "12pm–9pm" },
      { day: "Sunday", hours: "12pm–6pm" },
    ],
    tips: [
      { title: "Hours Change Seasonally", description: "Hours shift with the season and around special events; check the website before you go." },
      { title: "Friday Sunsets", description: "The winery runs Friday Sunsets music events on the patio." },
      { title: "Dogs on the Grass", description: "Dogs are allowed in the grass area during patio season." },
    ],
    whatToExpect: {
      atmosphere: "Lakefront winery and patio",
      crowd: "Couples, friend groups, wine club members",
      liveEvents: "Friday Sunsets and other music events",
      outdoorSeating: "Patio over Lake Waconia",
    },
    image: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800&q=80",
  },
  {
    slug: "lolas-lakehouse",
    name: "Lola's Lakehouse Eatery",
    category: "DINING",
    categoryLabel: "Lakeside Restaurant",
    categorySlugs: ["restaurants"],
    priceLevel: "$$",
    shortDescription: "Casual lakeside dining with a view",
    description:
      "A lakefront restaurant with views of Lake Waconia and a patio. The menu centers on fresh seafood, steaks and comfort food, with a full bar. Lola's also runs its own marina with seasonal boat slips.",
    address: "318 E Lake St, Waconia, MN 55387",
    lat: 44.8526,
    lng: -93.7867,
    phone: "(952) 442-4954",
    website: "lolaslakehouse.com",
    hours: [
      { day: "Monday", hours: "11am–9pm" },
      { day: "Tuesday", hours: "11am–9pm" },
      { day: "Wednesday", hours: "11am–9pm" },
      { day: "Thursday", hours: "11am–9pm" },
      { day: "Friday", hours: "11am–10pm" },
      { day: "Saturday", hours: "11am–10pm" },
      { day: "Sunday", hours: "11am–9pm" },
    ],
    tips: [
      { title: "Canadian Walleye", description: "The walleye on the menu is a Canadian walleye piccata." },
      { title: "Boat Slips", description: "Lola's rents seasonal slips at its marina through a waitlist." },
      { title: "Private Dining", description: "The patio and main dining room can be booked for private events." },
    ],
    whatToExpect: {
      atmosphere: "Casual lakeside, sunset-friendly",
      crowd: "Families, lake visitors, locals",
      liveEvents: "See website",
      outdoorSeating: "Yes, patio",
    },
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
  },
  {
    slug: "egg-cetera-cafe",
    name: "Egg-Cetera Cafe",
    category: "DINING",
    categoryLabel: "Breakfast & Brunch",
    categorySlugs: ["restaurants"],
    priceLevel: "$",
    shortDescription: "Mom-and-pop breakfast cafe",
    description:
      "A mom-and-pop breakfast cafe on East Frontage Road. It has no website; hours and specials are posted on its Facebook page.",
    address: "241 E Frontage Rd, Waconia, MN 55387",
    lat: 44.8502,
    lng: -93.7870,
    phone: "(952) 442-5441",
    website: "",
    hours: HOURS_VARIES,
    tips: [
      { title: "Check Facebook", description: "The cafe posts hours and updates on its Facebook page." },
      { title: "Call Ahead", description: "Call (952) 442-5441 to check hours or ask about a table." },
    ],
    whatToExpect: {
      atmosphere: "Small breakfast cafe",
      crowd: "Local regulars",
      liveEvents: "N/A",
      outdoorSeating: "See Facebook",
    },
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&q=80",
  },
  {
    slug: "mocha-monkey",
    name: "Mocha Monkey",
    category: "DINING",
    categoryLabel: "Coffee Shop",
    categorySlugs: ["restaurants"],
    priceLevel: "$",
    shortDescription: "Downtown coffee shop with its own roastery",
    description:
      "A downtown coffee shop founded in 2006 that roasts its own coffee. Espresso drinks, breakfast sandwiches, muffins and cinnamon rolls, and Bridgeman's ice cream. Mocha Monkey has two locations in Waconia; this is the downtown shop on Olive Street.",
    address: "115 S Olive St, Waconia, MN 55387",
    lat: 44.8497,
    lng: -93.7872,
    phone: "(952) 442-2853",
    website: "themochamonkey.com",
    hours: [
      { day: "Monday", hours: "7am–5pm" },
      { day: "Tuesday", hours: "7am–5pm" },
      { day: "Wednesday", hours: "7am–5pm" },
      { day: "Thursday", hours: "7am–5pm" },
      { day: "Friday", hours: "7am–5pm" },
      { day: "Saturday", hours: "7am–6pm" },
      { day: "Sunday", hours: "7am–6pm" },
    ],
    tips: [
      { title: "Sunday Bluegrass", description: "The downtown shop hosts a bluegrass jam on Sundays." },
      { title: "House Roastery", description: "Mocha Monkey roasts its own beans; bags are sold in the shop." },
      { title: "Ice Cream Too", description: "The shop serves Bridgeman's ice cream." },
    ],
    whatToExpect: {
      atmosphere: "Cozy local coffeehouse",
      crowd: "Locals, families, downtown visitors",
      liveEvents: "Sunday bluegrass jam",
      outdoorSeating: "See website",
    },
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&q=80",
  },
  {
    slug: "emagine-waconia",
    name: "Emagine Waconia",
    category: "RETAIL",
    categoryLabel: "Movie Theater",
    categorySlugs: ["things-to-do"],
    priceLevel: "$$",
    shortDescription: "Movie theater with power recliners and a bar",
    description:
      "Downtown Waconia's movie theater. Every auditorium has leather power-reclining seats, seating is reserved online or in the Emagine app, and the theater bar serves cocktails, beer and wine alongside concessions.",
    address: "101 W 1st St, Waconia, MN 55387",
    lat: 44.8590,
    lng: -93.7842,
    phone: "(952) 442-5885",
    website: "emagine-entertainment.com/theatres/emagine-waconia",
    hours: HOURS_VARIES,
    tips: [
      { title: "Reserve Seats", description: "Pick your seats in advance online or in the Emagine app." },
      { title: "$5 Ticket Tuesdays", description: "Emagine Rewards members get $5 tickets on Tuesdays; premium formats cost extra." },
      { title: "Showtimes Only", description: "The theater posts showtimes rather than fixed hours; check the website." },
    ],
    whatToExpect: {
      atmosphere: "Movie theater with recliners",
      crowd: "Families and date nights",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
  },
  {
    slug: "garage-bowling-bar",
    name: "Garage Bar & Bowl",
    category: "BARS",
    categoryLabel: "Entertainment",
    categorySlugs: ["things-to-do", "restaurants"],
    priceLevel: "$$",
    shortDescription: "Six-lane bowling alley with a bar and scratch kitchen",
    description:
      "A boutique six-lane bowling alley in downtown Waconia with a full bar and a scratch kitchen that uses locally sourced ingredients. Open bowling, leagues, and birthday and corporate party packages.",
    address: "16 W 1st St, Waconia, MN 55387",
    lat: 44.8515,
    lng: -93.7858,
    phone: "(952) 442-9999",
    website: "garagebowl.com",
    hours: [
      { day: "Monday", hours: "3pm–10pm" },
      { day: "Tuesday", hours: "3pm–10pm" },
      { day: "Wednesday", hours: "3pm–10pm" },
      { day: "Thursday", hours: "3pm–10pm" },
      { day: "Friday", hours: "3pm–11pm" },
      { day: "Saturday", hours: "11am–11pm" },
      { day: "Sunday", hours: "11am–10pm" },
    ],
    tips: [
      { title: "Open Bowling Hours Differ", description: "Open bowling runs shorter than the bar: none on Mondays, 3–9pm Tue–Thu, 3–10pm Fri, 11am–10pm Sat, 11am–9pm Sun." },
      { title: "Happy Hour", description: "Happy hour is 3–6pm Monday through Friday." },
      { title: "Party Packages", description: "Birthday and corporate packages need a reservation." },
    ],
    whatToExpect: {
      atmosphere: "Fun, casual, family-friendly",
      crowd: "Families, friend groups, leagues",
      liveEvents: "Leagues",
      outdoorSeating: "See website",
    },
    image: "https://images.unsplash.com/photo-1545232979-8bf68ee9b1af?w=800&q=80",
  },
  {
    slug: "island-view-golf-club",
    name: "Island View Golf Club",
    category: "RETAIL",
    categoryLabel: "Golf Course",
    categorySlugs: ["things-to-do"],
    priceLevel: "$$",
    shortDescription: "18-hole semi-private course, open to public play",
    description:
      "An 18-hole semi-private course just outside Waconia with rolling fairways and views toward Lake Waconia. Pro shop, full clubhouse with the Green Fox Grille restaurant, leagues, and event hosting.",
    address: "7795 Laketown Parkway, Waconia, MN 55387",
    lat: 44.8632,
    lng: -93.7549,
    phone: "(952) 442-6116",
    website: "islandviewgolfclub.com",
    hours: HOURS_VARIES,
    tips: [
      { title: "Public Tee Times", description: "Public tee times can be booked up to three days ahead." },
      { title: "Twilight Rate", description: "A twilight rate is offered on weekdays and weekends; check the website for start times." },
      { title: "Member Times", description: "The course is closed to public play Wednesdays 11am–1pm, Thursdays after 10am, and some Mondays." },
    ],
    whatToExpect: {
      atmosphere: "Suburban country club",
      crowd: "Golfers, league nights, weddings",
      liveEvents: "Member events and leagues",
      outdoorSeating: "Deck at the Green Fox Grille",
    },
    image: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=80",
  },
  {
    slug: "carver-county-historical-society",
    name: "Carver County Historical Society",
    category: "RETAIL",
    categoryLabel: "Museum",
    categorySlugs: ["things-to-do"],
    priceLevel: "$",
    shortDescription: "Free county history museum and research library",
    description:
      "Carver County's history museum and research library, free to visit. Galleries include the Akta Dakota exhibit and Choosing Carver County, with exhibits that change regularly. The Society also runs the Historic Andrew Peterson Farmstead, which hosts the free Fall on the Farm event on the fourth Saturday in September.",
    address: "555 W First St, Waconia, MN 55387",
    lat: 44.8506,
    lng: -93.7935,
    phone: "(952) 442-4234",
    website: "carvercountyhistoricalsociety.org",
    hours: [
      { day: "Monday", hours: "9am–4:30pm" },
      { day: "Tuesday", hours: "9am–4:30pm" },
      { day: "Wednesday", hours: "9am–4:30pm" },
      { day: "Thursday", hours: "9am–4:30pm" },
      { day: "Friday", hours: "9am–4:30pm" },
      { day: "Saturday", hours: "9am–2pm" },
      { day: "Sunday", hours: "Closed" },
    ],
    tips: [
      { title: "Free Admission", description: "There is no charge to visit the museum or the research library." },
      { title: "Research Help", description: "Staff help visitors with local history and genealogy research." },
      { title: "Fall on the Farm", description: "A free event at the Andrew Peterson Farmstead on the fourth Saturday in September, 10am–2pm, with barnyard animals and cooking over the fire pit." },
    ],
    whatToExpect: {
      atmosphere: "County history museum",
      crowd: "Families, researchers, school groups",
      liveEvents: "Programs and Fall on the Farm",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&q=80",
  },
  {
    slug: "waconia-public-library",
    name: "Waconia Public Library",
    category: "LOCAL SERVICES",
    categoryLabel: "Library",
    categorySlugs: ["services", "things-to-do"],
    priceLevel: "$",
    shortDescription: "Carver County library branch",
    description:
      "The Waconia branch of the Carver County Library, at 217 S Vine St in the City Hall complex. Books, programs for kids and adults, and the county's summer reading program.",
    address: "217 S Vine St, Waconia, MN 55387",
    lat: 44.8504,
    lng: -93.7873,
    phone: "(952) 303-0405",
    website: "carverlib.org",
    hours: [
      { day: "Monday", hours: "10am–8pm" },
      { day: "Tuesday", hours: "10am–8pm" },
      { day: "Wednesday", hours: "10am–6pm" },
      { day: "Thursday", hours: "10am–6pm" },
      { day: "Friday", hours: "10am–5pm" },
      { day: "Saturday", hours: "10am–3pm" },
      { day: "Sunday", hours: "Closed" },
    ],
    tips: [
      { title: "Library Cards", description: "Cards are for Carver County residents. If you live in another Minnesota county, you can register your home library card here." },
      { title: "Summer Reading", description: "The 2026 summer reading program ran June 1 to August 8." },
      { title: "Place Holds Online", description: "Request items through the Carver County Library catalog at carverlib.org." },
    ],
    whatToExpect: {
      atmosphere: "Quiet, welcoming, modern branch",
      crowd: "Families, students, retirees",
      liveEvents: "Library programs (see carverlib.org)",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80",
  },
  {
    slug: "ridgeview-medical-center",
    name: "Ridgeview Medical Center",
    category: "LOCAL SERVICES",
    categoryLabel: "Hospital",
    categorySlugs: ["services"],
    priceLevel: "$$",
    shortDescription: "Full-service hospital & clinics",
    description:
      "Ridgeview is the regional hospital for Waconia and western Carver County, offering emergency care, surgery, women's health, primary care, and a network of specialty clinics across the area.",
    address: "500 S Maple St, Waconia, MN 55387",
    lat: 44.8474,
    lng: -93.7896,
    phone: "(952) 442-2191",
    website: "ridgeviewmedical.org",
    hours: STANDARD_HOURS_24,
    tips: [
      { title: "Emergency Department", description: "Ridgeview's Waconia campus has an emergency department." },
      { title: "MyChart", description: "Use MyChart to message your provider and review records." },
      { title: "Urgent Care", description: "Ridgeview Urgent Care is at 560 S Maple St, Suite 30: Mon–Fri 8am–8pm, Sat–Sun 8am–5pm. (952) 442-1774." },
    ],
    whatToExpect: {
      atmosphere: "Modern regional hospital",
      crowd: "Patients and families across Carver County",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
  },
  {
    slug: "great-clips-waconia",
    name: "Great Clips",
    category: "LOCAL SERVICES",
    categoryLabel: "Hair Salon",
    categorySlugs: ["services"],
    priceLevel: "$",
    shortDescription: "Walk-in haircuts, online check-in",
    description:
      "A walk-in hair salon on Marketplace Drive offering haircuts for men, women and kids. You can join the waitlist online before you arrive.",
    address: "769 Marketplace Dr, Waconia, MN 55387",
    lat: 44.8627,
    lng: -93.7898,
    phone: "(952) 442-9840",
    website: "salons.greatclips.com/us/mn/waconia/769-marketplace-dr",
    hours: [
      { day: "Monday", hours: "10am–7pm" },
      { day: "Tuesday", hours: "10am–7pm" },
      { day: "Wednesday", hours: "10am–7pm" },
      { day: "Thursday", hours: "10am–7pm" },
      { day: "Friday", hours: "10am–7pm" },
      { day: "Saturday", hours: "8am–5pm" },
      { day: "Sunday", hours: "9am–3pm" },
    ],
    tips: [
      { title: "Online Check-In", description: "Join the waitlist online before you go. It isn't an appointment, but it saves time." },
      { title: "Clip Notes", description: "The salon saves your haircut details in Clip Notes for next time." },
    ],
    whatToExpect: {
      atmosphere: "Clean, modern salon",
      crowd: "Families and walk-in customers",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1585747860019-8e79b5b2fb1a?w=800&q=80",
  },
  {
    slug: "aldi-waconia",
    name: "Aldi Waconia",
    category: "LOCAL SERVICES",
    categoryLabel: "Grocery Store",
    categorySlugs: ["shopping"],
    priceLevel: "$",
    shortDescription: "Grocery store, everyday low prices",
    description:
      "Aldi offers high-quality groceries at everyday low prices. Known for efficient shopping, quality private-label products, and a streamlined store layout.",
    address: "10620 10th St W, Waconia, MN 55387",
    lat: 44.8624,
    lng: -93.7891,
    phone: "",
    website: "aldi.us",
    hours: [
      { day: "Monday", hours: "8:30am–8pm" },
      { day: "Tuesday", hours: "8:30am–8pm" },
      { day: "Wednesday", hours: "8:30am–8pm" },
      { day: "Thursday", hours: "8:30am–8pm" },
      { day: "Friday", hours: "8:30am–8pm" },
      { day: "Saturday", hours: "8:30am–8pm" },
      { day: "Sunday", hours: "8:30am–8pm" },
    ],
    tips: [
      { title: "Bring a Quarter", description: "Carts take a quarter, which you get back when you return the cart." },
      { title: "Bring Bags", description: "Bags are sold at checkout, so bring your own." },
      { title: "ALDI Finds", description: "The ALDI Finds aisle carries limited-time items that change weekly." },
    ],
    whatToExpect: {
      atmosphere: "Efficient, no-frills grocery shopping",
      crowd: "Local shoppers",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80",
  },
  {
    slug: "amerivu-inn-suites",
    name: "AmeriVu Inn & Suites",
    category: "RETAIL",
    categoryLabel: "Hotel & Lodging",
    categorySlugs: ["lodging"],
    priceLevel: "$$",
    shortDescription: "Hotel off Highway 5 with indoor pool",
    description:
      "A hotel in Waconia, off Highway 5. The non-smoking property has free breakfast, free WiFi and free parking, plus an indoor pool, hot tub and sauna. Pets are allowed for a fee.",
    address: "550 Cherry Dr, Waconia, MN 55387",
    lat: 44.8408,
    lng: -93.7979,
    phone: "(952) 442-8787",
    website: "amerivuinn.com/waconia",
    hours: STANDARD_HOURS_24,
    tips: [
      { title: "Pool, Hot Tub and Sauna", description: "The hotel has an indoor pool, a hot tub and a sauna." },
      { title: "Traveling With a Pet", description: "Pets are allowed and a pet fee applies. Confirm with the hotel when you book." },
      { title: "Free Breakfast", description: "Breakfast, WiFi and parking are free. Check-in is at 3pm." },
    ],
    whatToExpect: {
      atmosphere: "Clean, comfortable, family-friendly",
      crowd: "Tourists and business travelers",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
  },
  {
    slug: "dmv-waconia-mn",
    name: "Waconia DMV / Deputy Registrar",
    category: "LOCAL SERVICES",
    categoryLabel: "Government Services",
    categorySlugs: ["services"],
    priceLevel: "$",
    shortDescription: "Vehicle tabs, titles and DNR licenses",
    description:
      "Waconia's deputy registrar handles vehicle tabs, titles and registration, DNR registrations, fishing and hunting licenses, and disability plates. It does not handle first-time driver's licenses, renewals, name changes or REAL ID; those go to the Carver County License Center in Chaska.",
    address: "222 W Main St, Waconia, MN 55387",
    lat: 44.8507,
    lng: -93.7872,
    phone: "(952) 442-4038",
    website: "waconiamn.gov",
    hours: [
      { day: "Monday", hours: "7:30am–5pm" },
      { day: "Tuesday", hours: "7:30am–5pm" },
      { day: "Wednesday", hours: "7:30am–5pm" },
      { day: "Thursday", hours: "7:30am–5pm" },
      { day: "Friday", hours: "7:30am–1pm" },
      { day: "Saturday", hours: "Closed" },
      { day: "Sunday", hours: "Closed" },
    ],
    tips: [
      { title: "Driver's Licenses Go to Chaska", description: "For licenses, renewals and REAL ID, use the Carver County License Center, 418 Pine St, Chaska, (952) 361-1900." },
      { title: "Friday Closes at 1pm", description: "The office closes at 1pm on Fridays and is closed weekends." },
      { title: "Bring Current Registration", description: "Have your current registration with you for tab renewals." },
    ],
    whatToExpect: {
      atmosphere: "Government office, professional",
      crowd: "Local residents handling vehicle and ID needs",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
  },
  {
    slug: "deardorff-orchards",
    name: "Deardorff Orchards & Vineyards",
    category: "THINGS TO DO",
    categoryLabel: "Orchard & Farm",
    categorySlugs: ["things-to-do", "shopping"],
    priceLevel: "$",
    shortDescription: "Apple orchard on an 1888 farm, open fall weekends",
    description:
      "An apple orchard on a historic 1888 farm west of Waconia, with more than 3,000 apple trees on 120 acres, including SweeTango, Zestar!, Honeycrisp and Haralson. Open Saturdays and Sundays 12 to 6 during the 2026 apple season. A tractor-pulled wagon ride is free with a purchase of apples or wine. Parley Lake Winery's tasting room shares the barn.",
    address: "8282 Parley Lake Rd, Waconia, MN 55387",
    lat: 44.8762,
    lng: -93.8205,
    phone: "(612) 810-0606",
    website: "deardorfforchards.com",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "Closed" },
      { day: "Wednesday", hours: "Closed" },
      { day: "Thursday", hours: "Closed" },
      { day: "Friday", hours: "Closed" },
      { day: "Saturday", hours: "12pm–6pm" },
      { day: "Sunday", hours: "12pm–6pm" },
    ],
    tips: [
      { title: "Weekends Only", description: "The 2026 season runs Saturdays and Sundays, 12 to 6. Check the website for the season's end." },
      { title: "Wagon Ride", description: "The tractor-pulled wagon ride is free with a purchase of apples or wine." },
      { title: "Ask About Picking", description: "The orchard's website doesn't describe pick-your-own; call ahead if that's your plan." },
    ],
    whatToExpect: {
      atmosphere: "Working farm, classic Minnesota fall outing",
      crowd: "Families, fall visitors",
      liveEvents: "Live music and food on season weekends",
      outdoorSeating: "See website",
    },
    image: "/images/event-harvest-festival.webp",
  },
  {
    slug: "d-vincis-restaurant",
    name: "D'Vinci's Restaurant",
    category: "DINING",
    categoryLabel: "Italian Restaurant",
    categorySlugs: ["restaurants"],
    priceLevel: "$$",
    shortDescription: "Italian restaurant since 1986",
    description:
      "A Waconia Italian restaurant established in 1986, serving pizza, pasta, sandwiches and subs, with takeout and delivery.",
    address: "540 S Elm St, Waconia, MN 55387",
    lat: 44.8443,
    lng: -93.7863,
    phone: "(952) 442-2171",
    website: "dvinciswaconia.com",
    hours: [
      { day: "Monday", hours: "11am–9:30pm" },
      { day: "Tuesday", hours: "11am–9:30pm" },
      { day: "Wednesday", hours: "11am–9:30pm" },
      { day: "Thursday", hours: "11am–9:30pm" },
      { day: "Friday", hours: "11am–10pm" },
      { day: "Saturday", hours: "11am–10pm" },
      { day: "Sunday", hours: "11am–9:30pm" },
    ],
    tips: [
      { title: "Takeout and Delivery", description: "Takeout and delivery are available; the menu is on the restaurant's website." },
      { title: "Later on Weekends", description: "Open until 10pm Friday and Saturday, 9:30pm other nights." },
    ],
    whatToExpect: {
      atmosphere: "Casual Italian dining room",
      crowd: "Families and regulars",
      liveEvents: "N/A",
      outdoorSeating: "No",
    },
    image: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=800&q=80",
  },
  {
    slug: "bode-grays",
    name: "Bode Gray's",
    category: "DINING",
    categoryLabel: "Italian Restaurant & Cocktail Bar",
    categorySlugs: ["restaurants"],
    priceLevel: "$$",
    shortDescription: "Artisan pizza and Italian, downtown, since 2022",
    description:
      "A downtown Italian restaurant opened in 2022 with artisan pizza, pastas, lasagna and piccata. Reservations are taken through Tock. The Brass Hat, a 21+ speakeasy, is on the lower level.",
    address: "125 W 1st St, Waconia, MN 55387",
    lat: 44.8493,
    lng: -93.7881,
    phone: "(952) 444-0795",
    website: "bodegrays.com",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "4pm–9pm" },
      { day: "Wednesday", hours: "4pm–9pm" },
      { day: "Thursday", hours: "4pm–9pm" },
      { day: "Friday", hours: "4pm–9pm" },
      { day: "Saturday", hours: "4pm–9pm" },
      { day: "Sunday", hours: "4pm–8pm" },
    ],
    tips: [
      { title: "Reserve Through Tock", description: "Book a table through Tock from the restaurant's website." },
      { title: "The Brass Hat Downstairs", description: "The 21+ speakeasy on the lower level has live music Friday and Saturday nights." },
      { title: "Private Events", description: "The restaurant books private events; see its website." },
    ],
    whatToExpect: {
      atmosphere: "Downtown Italian dining room",
      crowd: "Date nights, downtown diners",
      liveEvents: "Live music downstairs at The Brass Hat",
      outdoorSeating: "See website",
    },
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
  },
  {
    slug: "the-brass-hat",
    name: "The Brass Hat",
    category: "BARS",
    categoryLabel: "Speakeasy Bar",
    categorySlugs: ["restaurants", "things-to-do"],
    priceLevel: "$$",
    shortDescription: "21+ speakeasy on Bode Gray's lower level",
    description:
      "A 21+ speakeasy on the lower level of Bode Gray's in downtown Waconia. It holds around 50 guests, has live music on Friday and Saturday nights, offers paid memberships, and serves a limited Bode Gray's menu.",
    address: "125 W 1st St, Waconia, MN 55387",
    lat: 44.8493,
    lng: -93.7881,
    phone: "(952) 444-0795",
    website: "bodegrays.com/the-brass-hat",
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "From 4pm" },
      { day: "Wednesday", hours: "From 4pm" },
      { day: "Thursday", hours: "From 4pm" },
      { day: "Friday", hours: "From 4pm" },
      { day: "Saturday", hours: "From 4pm" },
      { day: "Sunday", hours: "Closed" },
    ],
    tips: [
      { title: "21 and Over", description: "The Brass Hat is 21+ only." },
      { title: "Live Music Weekends", description: "Live music runs Friday and Saturday, 7–10pm, first come, first served." },
      { title: "Small Room", description: "The space holds about 50 people, so arrive early on music nights." },
    ],
    whatToExpect: {
      atmosphere: "Moody, intimate speakeasy lounge",
      crowd: "Adults 21+, couples, cocktail drinkers",
      liveEvents: "Live music Fri–Sat 7–10pm",
      outdoorSeating: "No",
    },
    image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80",
  },
  {
    slug: "green-fox-grille",
    name: "Green Fox Grille",
    category: "DINING",
    categoryLabel: "Golf Course Grille",
    categorySlugs: ["restaurants", "things-to-do"],
    priceLevel: "$$",
    shortDescription: "Clubhouse grille at Island View Golf Club",
    description:
      "The clubhouse restaurant at Island View Golf Club — custom-blend burgers, hand-crafted sandwiches, tap beer, and seasonal cocktails. Open to the public, not just golfers, with a deck overlooking Lake Waconia and the course, plus indoor seating down the 18th fairway. Also books weddings and private events.",
    address: "7795 Laketown Parkway, Waconia, MN 55387",
    lat: 44.8632,
    lng: -93.7549,
    phone: "(952) 442-6116",
    website: "greenfoxgrille.com",
    hours: [
      { day: "Monday", hours: "11am–8pm" },
      { day: "Tuesday", hours: "11am–8pm" },
      { day: "Wednesday", hours: "11am–8pm" },
      { day: "Thursday", hours: "11am–8pm" },
      { day: "Friday", hours: "11am–9pm" },
      { day: "Saturday", hours: "11am–9pm" },
      { day: "Sunday", hours: "11am–8pm" },
    ],
    tips: [
      { title: "Open to Non-Golfers", description: "You don't need to play a round — the grille and deck are open to the public." },
      { title: "Deck Seating in Summer", description: "The outdoor deck overlooking the lake and course is the draw — request it when you arrive." },
      { title: "Event Booking", description: "Available for weddings, private groups, and corporate events — inquire through the golf club." },
    ],
    whatToExpect: {
      atmosphere: "Casual clubhouse grille with lake and fairway views",
      crowd: "Golfers, families, event guests",
      liveEvents: "Private events and weddings",
      outdoorSeating: "Yes — deck overlooking Lake Waconia",
    },
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
  },
  {
    slug: "culvers-waconia",
    name: "Culver's",
    category: "DINING",
    categoryLabel: "Fast Casual",
    categorySlugs: ["restaurants"],
    priceLevel: "$",
    shortDescription: "ButterBurgers & frozen custard",
    description:
      "The Waconia Culver's: ButterBurgers, Wisconsin cheese curds and frozen custard with a daily Flavor of the Day. Dine-in, drive-thru and curbside service.",
    address: "10710 10th St, Waconia, MN 55387",
    lat: 44.8392,
    lng: -93.7959,
    phone: "(952) 442-4471",
    website: "culvers.com/restaurants/waconia-mn-hwy-5",
    hours: [
      { day: "Monday", hours: "10am–10pm" },
      { day: "Tuesday", hours: "10am–10pm" },
      { day: "Wednesday", hours: "10am–10pm" },
      { day: "Thursday", hours: "10am–10pm" },
      { day: "Friday", hours: "10am–10pm" },
      { day: "Saturday", hours: "10am–10pm" },
      { day: "Sunday", hours: "10am–10pm" },
    ],
    tips: [
      { title: "Flavor of the Day", description: "The custard Flavor of the Day calendar is on the restaurant's page." },
      { title: "Drive-Thru", description: "Drive-thru is open the same hours as the dining room, 10am to 10pm." },
    ],
    whatToExpect: {
      atmosphere: "Bright, casual fast-food dining room",
      crowd: "Families, quick lunch and dinner stops",
      liveEvents: "N/A",
      outdoorSeating: "Seasonal patio",
    },
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80",
  },
  {
    slug: "caribou-coffee-waconia",
    name: "Caribou Coffee",
    category: "DINING",
    categoryLabel: "Coffee Shop",
    categorySlugs: ["restaurants"],
    priceLevel: "$",
    shortDescription: "Two Waconia locations, one with a drive-thru",
    description:
      "Caribou has two Waconia locations. This one is inside Mackenthun's Fine Foods on Marketplace Drive, with walk-in and curbside service. The second, at 77 Highway 5 West, has a drive-thru and longer hours (Mon–Fri 5:30am–7pm, Sat 6am–7pm, Sun 6:30am–7pm; (952) 219-7365).",
    address: "851 Marketplace Dr, Waconia, MN 55387",
    lat: 44.8365,
    lng: -93.7996,
    phone: "(952) 442-2512",
    website: "cariboucoffee.com",
    hours: [
      { day: "Monday", hours: "6am–5pm" },
      { day: "Tuesday", hours: "6am–5pm" },
      { day: "Wednesday", hours: "6am–5pm" },
      { day: "Thursday", hours: "6am–5pm" },
      { day: "Friday", hours: "6am–5pm" },
      { day: "Saturday", hours: "6am–5pm" },
      { day: "Sunday", hours: "6am–5pm" },
    ],
    tips: [
      { title: "Drive-Thru Is on Highway 5", description: "Only the Highway 5 West location has a drive-thru; the Marketplace Drive location is inside Mackenthun's." },
      { title: "Mobile Order", description: "Order ahead with Caribou's Mobile Order and Pay." },
      { title: "Caribou Perks", description: "Caribou's rewards program is Caribou Perks." },
    ],
    whatToExpect: {
      atmosphere: "Bright, quick-service coffeehouse",
      crowd: "Commuters, families, remote workers",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
  },
  {
    slug: "waconia-public-schools-isd-110",
    name: "Waconia Public Schools (ISD 110)",
    category: "LOCAL SERVICES",
    categoryLabel: "School District",
    categorySlugs: ["services"],
    priceLevel: "$",
    shortDescription: "Independent School District 110",
    description:
      "Independent School District 110, Waconia Public Schools: Waconia High School, Waconia Middle School, and three elementary schools (Bayview, Laketown and Southview). Waconia competes in the Metro West Conference; the mascot is the Wildcats. The district office is at 512 Industrial Blvd.",
    address: "512 Industrial Blvd, Waconia, MN 55387",
    lat: 44.8460,
    lng: -93.7754,
    phone: "(952) 442-0600",
    website: "isd110.org",
    hours: [
      { day: "Monday", hours: "7:30am–4pm" },
      { day: "Tuesday", hours: "7:30am–4pm" },
      { day: "Wednesday", hours: "7:30am–4pm" },
      { day: "Thursday", hours: "7:30am–4pm" },
      { day: "Friday", hours: "7:30am–4pm" },
      { day: "Saturday", hours: "Closed" },
      { day: "Sunday", hours: "Closed" },
    ],
    tips: [
      { title: "Check Boundaries", description: "The district publishes an interactive boundary map at isd110.org." },
      { title: "Community Education", description: "Community Education (516 Industrial Blvd, (952) 442-0610) runs preschool, ECFE, KidSpace childcare, youth recreation and adult classes." },
      { title: "Hours Shown", description: "Hours are for the district office." },
    ],
    whatToExpect: {
      atmosphere: "Modern suburban school district",
      crowd: "Families, students, community members",
      liveEvents: "Athletics, arts performances, school board meetings",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
  },
  {
    slug: "johnson-funeral-home",
    name: "Johnson Funeral Home",
    category: "LOCAL SERVICES",
    categoryLabel: "Funeral Home",
    categorySlugs: ["services"],
    priceLevel: "",
    shortDescription: "Funeral home in downtown Waconia",
    description:
      "Johnson Funeral Home is a funeral home on 1st Street East in downtown Waconia. Current obituaries and service times are posted on the funeral home's own website.",
    address: "141 1st St E, Waconia, MN 55387",
    lat: 44.8491,
    lng: -93.7834,
    phone: "(952) 442-2121",
    website: "johnsonfh.com",
    hours: HOURS_VARIES,
    tips: [
      { title: "Obituaries", description: "Recent obituaries and service details are listed at johnsonfh.com." },
      { title: "Call Directly", description: "For arrangements or questions about a service, call (952) 442-2121." },
      { title: "Flowers", description: "The funeral home's website has a Send Flowers link." },
    ],
    whatToExpect: {
      atmosphere: "Funeral home in downtown Waconia",
      crowd: "Families and friends attending services",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "/images/hero-lake-waconia.webp",
  },
  {
    slug: "lakeview-clinic-waconia",
    name: "Lakeview Clinic",
    category: "LOCAL SERVICES",
    categoryLabel: "Medical Clinic",
    categorySlugs: ["services"],
    priceLevel: "",
    shortDescription: "Medical clinic on Highway 5, open Saturday mornings",
    description:
      "Lakeview Clinic's Waconia location is a medical clinic on Highway 5 West. It is open weekdays and Saturday mornings, and the clinic lists same-day services.",
    address: "424 State Hwy 5 W, Waconia, MN 55387",
    lat: 44.8416,
    lng: -93.7937,
    phone: "(952) 442-4461",
    website: "lakeviewclinic.com",
    hours: [
      { day: "Monday", hours: "8am–5pm" },
      { day: "Tuesday", hours: "8am–5pm" },
      { day: "Wednesday", hours: "8am–5pm" },
      { day: "Thursday", hours: "8am–5pm" },
      { day: "Friday", hours: "8am–5pm" },
      { day: "Saturday", hours: "8am–12pm" },
      { day: "Sunday", hours: "Closed" },
    ],
    tips: [
      { title: "Same-Day Care", description: "The clinic lists same-day services. Call (952) 442-4461 to check availability." },
      { title: "Saturday Mornings", description: "Open 8am to noon on Saturdays; closed Sundays." },
      { title: "Emergencies", description: "Ridgeview Medical Center's emergency department in Waconia is open 24/7." },
    ],
    whatToExpect: {
      atmosphere: "Medical clinic",
      crowd: "Patients from Waconia and nearby towns",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
  },
  {
    slug: "safari-island-community-center",
    name: "Safari Island Community Center",
    category: "LOCAL SERVICES",
    categoryLabel: "Community Center & Indoor Pool",
    categorySlugs: ["things-to-do", "services"],
    priceLevel: "",
    shortDescription: "Indoor pool with a 175-foot slide, play structure, gym and track",
    description:
      "Safari Island is Waconia's community center. It has an indoor zero-depth entry pool with a 175-foot slide, a lap pool with one-meter diving boards, a spa, the Lion's Den four-level indoor play structure, a fitness center, an indoor track, a four-court gymnasium and batting cages.",
    address: "1600 Community Dr, Waconia, MN 55387",
    lat: 44.8362,
    lng: -93.8197,
    phone: "(952) 442-0695",
    website: "safariislandcommunitycenter.com",
    hours: [
      { day: "Monday", hours: "5:30am–9pm" },
      { day: "Tuesday", hours: "5:30am–9pm" },
      { day: "Wednesday", hours: "5:30am–9pm" },
      { day: "Thursday", hours: "5:30am–9pm" },
      { day: "Friday", hours: "5:30am–9pm" },
      { day: "Saturday", hours: "7am–6pm" },
      { day: "Sunday", hours: "8am–6pm" },
    ],
    tips: [
      { title: "Check Pool Times", description: "Pool and slide hours can differ from building hours. Check the center's website before you go." },
      { title: "Lion's Den", description: "The four-level indoor play structure is the draw for younger kids on cold days." },
      { title: "Passes and Rates", description: "Day pass and membership prices are on the center's website." },
    ],
    whatToExpect: {
      atmosphere: "Busy family recreation center",
      crowd: "Families, swimmers and gym members",
      liveEvents: "See website",
      outdoorSeating: "N/A",
    },
    image: "/images/conservation-lake-waconia.webp",
  },
  {
    slug: "waconia-ice-arena",
    name: "Waconia Ice Arena",
    category: "LOCAL SERVICES",
    categoryLabel: "Ice Arena",
    categorySlugs: ["things-to-do"],
    priceLevel: "",
    shortDescription: "Open skate, open hockey and skating lessons",
    description:
      "Waconia Ice Arena is owned by the City of Waconia and operated by Sports Facilities Companies. It runs open skate sessions, open hockey and Learn to Skate lessons.",
    address: "1250 Oak Ave, Waconia, MN 55387",
    lat: 44.836,
    lng: -93.8085,
    phone: "(952) 442-7465",
    website: "waconiaicearena.com",
    hours: HOURS_VARIES,
    tips: [
      { title: "Open Skate Schedule", description: "Open skate times change through the season. The current schedule is on the arena's website." },
      { title: "Learn to Skate", description: "The arena runs skating lessons; sign-up details are on its website." },
      { title: "Open Hockey", description: "Open hockey sessions are listed on the arena's schedule." },
    ],
    whatToExpect: {
      atmosphere: "Indoor ice rink",
      crowd: "Skaters, hockey players and families",
      liveEvents: "See website",
      outdoorSeating: "N/A",
    },
    image: "/images/hero-lake-waconia.webp",
  },
  {
    slug: "pangea-cafe",
    name: "Pangea Cafe",
    category: "DINING",
    categoryLabel: "Breakfast & Lunch Cafe",
    categorySlugs: ["restaurants"],
    priceLevel: "",
    shortDescription: "Downtown breakfast and lunch, all-day breakfast",
    description:
      "Pangea Cafe serves breakfast and lunch on West 1st Street in downtown Waconia. Breakfast is available all day; lunch is served Monday through Saturday from 11am to 2pm, and Sunday is breakfast only.",
    address: "37 W 1st St, Waconia, MN 55387",
    lat: 44.8493,
    lng: -93.7867,
    phone: "(952) 300-8604",
    website: "pangeacafemn.com",
    hours: [
      { day: "Monday", hours: "8am–2pm" },
      { day: "Tuesday", hours: "8am–2pm" },
      { day: "Wednesday", hours: "8am–2pm" },
      { day: "Thursday", hours: "8am–2pm" },
      { day: "Friday", hours: "8am–2pm" },
      { day: "Saturday", hours: "8am–2pm" },
      { day: "Sunday", hours: "8am–2pm" },
    ],
    tips: [
      { title: "Reserve on Weekends", description: "The cafe encourages reservations, especially on weekends. Walk-ins are also taken." },
      { title: "Sunday Is Breakfast Only", description: "Lunch is served Monday through Saturday, 11am to 2pm." },
      { title: "Takeout", description: "The menus are available for takeout. The cafe asks you to call ahead: (952) 300-8604." },
    ],
    whatToExpect: {
      atmosphere: "Downtown breakfast and lunch cafe",
      crowd: "Locals and weekend visitors",
      liveEvents: "See website",
      outdoorSeating: "See website",
    },
    image: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&q=80",
  },
  {
    slug: "mackenthuns-fine-foods",
    name: "Mackenthun's Fine Foods",
    category: "LOCAL SERVICES",
    categoryLabel: "Grocery Store",
    categorySlugs: ["shopping"],
    priceLevel: "",
    shortDescription: "Full-service grocery with pharmacy and Caribou Coffee",
    description:
      "Mackenthun's Fine Foods is a full-service grocery store on Marketplace Drive with produce, a meat department and a scratch bakery. The store also has a pharmacy and a Caribou Coffee, and offers online ordering for pickup or delivery.",
    address: "851 Marketplace Dr, Waconia, MN 55387",
    lat: 44.8363,
    lng: -93.8,
    phone: "(952) 442-2512",
    website: "mackenthuns.com",
    hours: [
      { day: "Monday", hours: "6am–10pm" },
      { day: "Tuesday", hours: "6am–10pm" },
      { day: "Wednesday", hours: "6am–10pm" },
      { day: "Thursday", hours: "6am–10pm" },
      { day: "Friday", hours: "6am–10pm" },
      { day: "Saturday", hours: "6am–10pm" },
      { day: "Sunday", hours: "6am–10pm" },
    ],
    tips: [
      { title: "Pharmacy Hours", description: "The in-store pharmacy is open Monday to Friday 8am–7pm and Saturday 9am–3pm; closed Sunday." },
      { title: "Caribou Coffee", description: "The in-store Caribou is open 6am to 5pm." },
      { title: "Order Online", description: "Groceries can be ordered online for pickup or delivery." },
    ],
    whatToExpect: {
      atmosphere: "Full-service neighborhood grocery",
      crowd: "Local shoppers",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
  },
  {
    slug: "target-waconia",
    name: "Target",
    category: "LOCAL SERVICES",
    categoryLabel: "Department Store",
    categorySlugs: ["shopping"],
    priceLevel: "",
    shortDescription: "Target with CVS pharmacy, MinuteClinic and Starbucks",
    description:
      "The Waconia Target is on East Main Street. The store has a CVS pharmacy, a MinuteClinic and a Starbucks Cafe, and offers Order Pickup, Drive Up and same-day delivery.",
    address: "875 E Main St, Waconia, MN 55387",
    lat: 44.8406,
    lng: -93.7712,
    phone: "(952) 442-9333",
    website: "target.com/sl/waconia/2449",
    hours: [
      { day: "Monday", hours: "7am–10pm" },
      { day: "Tuesday", hours: "7am–10pm" },
      { day: "Wednesday", hours: "7am–10pm" },
      { day: "Thursday", hours: "7am–10pm" },
      { day: "Friday", hours: "7am–10pm" },
      { day: "Saturday", hours: "7am–10pm" },
      { day: "Sunday", hours: "7am–10pm" },
    ],
    tips: [
      { title: "CVS Pharmacy", description: "The pharmacy keeps shorter hours than the store and closes for a midday break. Its direct line is (952) 442-9334." },
      { title: "Drive Up", description: "Order in the Target app and have it brought to your car." },
      { title: "Holiday Hours", description: "Hours change around holidays. Check the store page before you go." },
    ],
    whatToExpect: {
      atmosphere: "Standard Target store",
      crowd: "Shoppers from Waconia and western Carver County",
      liveEvents: "N/A",
      outdoorSeating: "N/A",
    },
    image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80",
  },
];

export function getBusinessBySlug(slug: string): Business | undefined {
  return businesses.find((b) => b.slug === slug);
}

export function getBusinessesByCategory(slug: CategorySlug): Business[] {
  return businesses.filter((b) => b.categorySlugs.includes(slug));
}

export function getRelatedBusinesses(
  currentSlug: string,
  limit = 4
): Business[] {
  const current = getBusinessBySlug(currentSlug);
  if (!current) return businesses.filter((b) => b.slug !== currentSlug).slice(0, limit);

  // Prefer businesses sharing a category with the current one.
  const sameCategory = businesses.filter(
    (b) =>
      b.slug !== currentSlug &&
      b.categorySlugs.some((c) => current.categorySlugs.includes(c)),
  );
  const others = businesses.filter(
    (b) => b.slug !== currentSlug && !sameCategory.includes(b),
  );
  return [...sameCategory, ...others].slice(0, limit);
}
